language: generic 
sudo: required
services:
  - docker

before install:
  - docker build -t anu123bgs/docker-react -f Dockerfile.dev .

script:
  - docker run anu123bgs/docker-react npm run test -- --coverage